# permissions for end users to edit swansons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: swanson-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: swansonator
    app.kubernetes.io/part-of: swansonator
    app.kubernetes.io/managed-by: kustomize
  name: swanson-editor-role
rules:
- apiGroups:
  - parks.department.com
  resources:
  - swansons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - parks.department.com
  resources:
  - swansons/status
  verbs:
  - get
