apiVersion: cache.jacobboykin.com/v1alpha1
kind: Swanson
metadata:
  labels:
    app.kubernetes.io/name: swanson
    app.kubernetes.io/instance: swanson-sample
    app.kubernetes.io/part-of: swansoner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: swansoner
  name: swanson-sample
spec:
  # TODO(user): Add fields here
